//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicLocalizationSample.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynamicLocalizationSample.Resources.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Me.
        /// </summary>
        internal static string Click_Me {
            get {
                return ResourceManager.GetString("Click_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled Input.
        /// </summary>
        internal static string Disabled_Input {
            get {
                return ResourceManager.GetString("Disabled_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Localization App.
        /// </summary>
        internal static string Dynamic_Localization_App {
            get {
                return ResourceManager.GetString("Dynamic_Localization_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Option.
        /// </summary>
        internal static string First_Option {
            get {
                return ResourceManager.GetString("First_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouped Controls.
        /// </summary>
        internal static string Grouped_Controls {
            get {
                return ResourceManager.GetString("Grouped_Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Option.
        /// </summary>
        internal static string Second_Option {
            get {
                return ResourceManager.GetString("Second_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a another text block.
        /// </summary>
        internal static string This_Is_A_Another_Text_Block {
            get {
                return ResourceManager.GetString("This_Is_A_Another_Text_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a text block.
        /// </summary>
        internal static string This_Is_A_Text_Block {
            get {
                return ResourceManager.GetString("This_Is_A_Text_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yet another text block.
        /// </summary>
        internal static string Yet_A_Another_Text_Block {
            get {
                return ResourceManager.GetString("Yet_A_Another_Text_Block", resourceCulture);
            }
        }
    }
}
